from tools.run_cuda_candidate_case import DEFAULT_CUDA_FLAGS


def test_cuda_candidate_keeps_precomputed_unsfin_reference_grid_guard_by_default():
    assert DEFAULT_CUDA_FLAGS["EDDA_EXPERIMENT_VALIDATE_PRECOMPUTED_UNSFIN_FAILURE_GRID_MATCH"] == "1"
    assert DEFAULT_CUDA_FLAGS["EDDA_EXPERIMENT_RNOFF_NATIVE_UNSFIN_FEED"] == "1"
    assert DEFAULT_CUDA_FLAGS["EDDA_NATIVE_UNSFIN_RUNTIME_FEED"] == "1"
    assert DEFAULT_CUDA_FLAGS["EDDA_EXPERIMENT_DFS_SOURCE_STAGING_FIELD"] == "1"
    assert DEFAULT_CUDA_FLAGS["EDDA_EXPERIMENT_DFS_SOURCE_STAGING_FAST_CONSUME"] == "1"
    assert DEFAULT_CUDA_FLAGS["EDDA_EXPERIMENT_DFS_SOURCE_STAGING_KERNEL"] == "1"
