"""Default-off stormdrain topology loader and runtime diagnostic helper.

The implementation follows the visible original EDDA ``readdrainage.f90``,
``dfs.F90`` drainage-exchange block, and the first dry-network branch of
``dwflow.f90``.  It is intentionally gated by
``EDDA_EXPERIMENT_STORMDRAIN=1`` and fails closed on malformed topology.
"""
from __future__ import annotations

from dataclasses import dataclass
import math
import os
from pathlib import Path
from typing import Mapping, Sequence


STORMDRAIN_RUNTIME_FLAG = "EDDA_EXPERIMENT_STORMDRAIN"
# Original dwflow.f90 assigns default-real literals into double precision state.
STORMDRAIN_DRY_FUDGE_M = 9.999999747378752e-05
STORMDRAIN_NODE_SURFACE_AREA_M2 = 1.4860000610351562
STORMDRAIN_NODE_STORAGE_AREA_M2 = 1.485999941825867
STORMDRAIN_LOW_DEPTH_WEIR_COEFF = 2.4384 * 3.3
STORMDRAIN_GRAVITY = 9.81


@dataclass(frozen=True)
class StormdrainNode:
    node_no: int
    name: str
    nodeindex: int
    nodetype: int
    invertel_m: float
    nmaxdepth_m: float


@dataclass(frozen=True)
class StormdrainConduit:
    conduit_no: int
    name: str
    inlet_node: int
    outlet_node: int
    length_m: float
    manningn: float
    xsecshpindx: int
    cmaxdepth_m: float
    geom2: float


@dataclass(frozen=True)
class StormdrainTopology:
    drainage_path: str
    nodes: tuple[StormdrainNode, ...]
    conduits: tuple[StormdrainConduit, ...]

    @property
    def node_count(self) -> int:
        return len(self.nodes)

    @property
    def conduit_count(self) -> int:
        return len(self.conduits)


class StormdrainTopologyError(ValueError):
    """Raised when original EDDA drainage topology is missing or malformed."""


def stormdrain_runtime_enabled(environ: Mapping[str, str] | None = None) -> bool:
    values = os.environ if environ is None else environ
    return str(values.get(STORMDRAIN_RUNTIME_FLAG, "")).strip() == "1"


def _clean_lines(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text(encoding="utf-8", errors="ignore").splitlines() if line.strip()]


def _read_int_line(lines: Sequence[str], index: int, *, label: str) -> int:
    try:
        return int(lines[index].split()[0])
    except Exception as exc:
        raise StormdrainTopologyError(f"Malformed drainage.txt {label} at line {index + 1}: {lines[index]!r}") from exc


def load_stormdrain_topology(
    drainage_path: str | Path,
    *,
    imax: int | None = None,
) -> StormdrainTopology:
    """Parse original ``drainage.txt`` topology generated by ``getdwinput``."""
    path = Path(drainage_path)
    if not path.is_file():
        raise FileNotFoundError(f"missing drainage topology file: {path}")
    lines = _clean_lines(path)
    if len(lines) < 5:
        raise StormdrainTopologyError(f"Malformed drainage.txt: expected header and node count in {path}")

    node_count = _read_int_line(lines, 2, label="node count")
    node_start = 4
    node_end = node_start + node_count
    if len(lines) <= node_end + 2:
        raise StormdrainTopologyError(f"Malformed drainage.txt: incomplete node/conduit sections in {path}")

    nodes: list[StormdrainNode] = []
    for offset, line in enumerate(lines[node_start:node_end], start=node_start + 1):
        parts = line.split()
        if len(parts) < 5:
            raise StormdrainTopologyError(f"Malformed drainage node row at line {offset}: {line!r}")
        try:
            nodeindex = int(parts[1])
            nodetype = int(parts[2])
            invertel = float(parts[3])
            nmaxdepth = float(parts[4])
        except Exception as exc:
            raise StormdrainTopologyError(f"Malformed drainage node row at line {offset}: {line!r}") from exc
        if nodeindex <= 0:
            raise StormdrainTopologyError(f"Invalid drainage nodeindex {nodeindex} at line {offset}")
        if imax is not None and nodeindex > int(imax):
            raise StormdrainTopologyError(f"Drainage nodeindex {nodeindex} exceeds imax {imax} at line {offset}")
        if nodetype not in (0, 1):
            raise StormdrainTopologyError(f"Invalid drainage nodetype {nodetype} at line {offset}")
        if not math.isfinite(invertel) or not math.isfinite(nmaxdepth):
            raise StormdrainTopologyError(f"Non-finite drainage node numeric value at line {offset}")
        nodes.append(
            StormdrainNode(
                node_no=len(nodes) + 1,
                name=parts[0],
                nodeindex=nodeindex,
                nodetype=nodetype,
                invertel_m=invertel,
                nmaxdepth_m=nmaxdepth,
            )
        )

    conduit_count_index = node_end + 1
    conduit_count = _read_int_line(lines, conduit_count_index, label="conduit count")
    conduit_start = conduit_count_index + 2
    conduit_end = conduit_start + conduit_count
    if len(lines) < conduit_end:
        raise StormdrainTopologyError(f"Malformed drainage.txt: expected {conduit_count} conduit rows in {path}")

    conduits: list[StormdrainConduit] = []
    for offset, line in enumerate(lines[conduit_start:conduit_end], start=conduit_start + 1):
        parts = line.split()
        if len(parts) < 8:
            raise StormdrainTopologyError(f"Malformed drainage conduit row at line {offset}: {line!r}")
        try:
            inlet = int(parts[1])
            outlet = int(parts[2])
            length = float(parts[3])
            manningn = float(parts[4])
            xsec = int(parts[5])
            cmaxdepth = float(parts[6])
            geom2 = float(parts[7])
        except Exception as exc:
            raise StormdrainTopologyError(f"Malformed drainage conduit row at line {offset}: {line!r}") from exc
        if inlet < 1 or inlet > node_count or outlet < 1 or outlet > node_count:
            raise StormdrainTopologyError(f"Invalid conduit endpoint at line {offset}: inlet={inlet}, outlet={outlet}")
        if xsec not in (1, 2):
            raise StormdrainTopologyError(f"Unsupported conduit xsecshpindx {xsec} at line {offset}")
        numeric_values = (length, manningn, cmaxdepth, geom2)
        if any(not math.isfinite(value) for value in numeric_values):
            raise StormdrainTopologyError(f"Non-finite drainage conduit numeric value at line {offset}")
        if length <= 0.0 or cmaxdepth < 0.0:
            raise StormdrainTopologyError(f"Invalid conduit length/depth at line {offset}")
        conduits.append(
            StormdrainConduit(
                conduit_no=len(conduits) + 1,
                name=parts[0],
                inlet_node=inlet,
                outlet_node=outlet,
                length_m=length,
                manningn=manningn,
                xsecshpindx=xsec,
                cmaxdepth_m=cmaxdepth,
                geom2=geom2,
            )
        )

    return StormdrainTopology(drainage_path=str(path), nodes=tuple(nodes), conduits=tuple(conduits))


def _mapping_values(values: Mapping[int, float] | Sequence[float], *, name: str) -> dict[int, float]:
    if isinstance(values, Mapping):
        result = {int(key): float(value) for key, value in values.items()}
    else:
        result = {index: float(value) for index, value in enumerate(values) if index > 0}
    bad = [key for key, value in result.items() if key <= 0 or not math.isfinite(value)]
    if bad:
        raise ValueError(f"{name} contains invalid one-based cell values: {bad[:5]}")
    return result


def _default_runtime_manifest(
    *,
    enabled: bool,
    drainage_path: str | Path | None,
) -> dict[str, object]:
    path = None if drainage_path is None else str(drainage_path)
    return {
        "stormdrain_available": bool(path) and Path(path).is_file(),
        "stormdrain_selected": enabled,
        "stormdrain_runtime_enabled": enabled,
        "stormdrain_branch_active": False,
        "topology_loaded": False,
        "drainage_topology_validated": False,
        "node_count": 0,
        "conduit_count": 0,
        "node_trace_row_count": 0,
        "conduit_trace_row_count": 0,
        "dw_nodal_flow_expected_rows": 0,
        "dw_conduit_flow_expected_rows": 0,
        "changed_field_names": [],
        "blocked_reason": None,
        "fail_closed": False,
        "default_off_verified": not enabled,
        "drainage_path": path,
        "node_exchange": [],
        "dwflow_nodes": [],
        "dwflow_conduits": [],
        "balance": {},
        "topology": {"nodes": [], "conduits": []},
        "topology_summary": {},
        "oracle_comparable_metrics": {},
        "mutation_contract": {
            "dfs_equations_changed": False,
            "dfs_face_connectivity_changed": False,
            "hydrograph_exporter_changed": False,
            "inflow_denominator_changed": False,
            "native_unsfin_schedule_changed": False,
            "rnoff_behavior_changed": False,
        },
    }


def _topology_summary(topology: StormdrainTopology, *, imax: int | None) -> dict[str, object]:
    node_indexes = [node.nodeindex for node in topology.nodes]
    node_names = [node.name for node in topology.nodes]
    conduit_names = [conduit.name for conduit in topology.conduits]
    return {
        "format": "original readdrainage.f90 drainage.txt",
        "imax": imax,
        "nodeindex_min": min(node_indexes) if node_indexes else None,
        "nodeindex_max": max(node_indexes) if node_indexes else None,
        "junction_count": sum(1 for node in topology.nodes if node.nodetype == 0),
        "outfall_count": sum(1 for node in topology.nodes if node.nodetype == 1),
        "duplicate_node_name_count": len(node_names) - len(set(node_names)),
        "duplicate_conduit_name_count": len(conduit_names) - len(set(conduit_names)),
        "one_based_indexing": True,
        "source_read_location": "readdrainage.f90 reads non/noc and stormdrain_vars node/conduit arrays",
    }


def _topology_only_result(topology: StormdrainTopology, *, imax: int | None) -> dict[str, object]:
    node_count = topology.node_count
    conduit_count = topology.conduit_count
    return {
        "stormdrain_available": True,
        "stormdrain_selected": True,
        "stormdrain_runtime_enabled": True,
        "stormdrain_branch_active": True,
        "topology_loaded": True,
        "drainage_topology_validated": True,
        "node_count": node_count,
        "conduit_count": conduit_count,
        "node_trace_row_count": node_count,
        "conduit_trace_row_count": conduit_count,
        "dw_nodal_flow_expected_rows": node_count,
        "dw_conduit_flow_expected_rows": conduit_count,
        "changed_field_names": [],
        "blocked_reason": None,
        "fail_closed": False,
        "default_off_verified": False,
        "topology": {
            "nodes": [node.__dict__ for node in topology.nodes],
            "conduits": [conduit.__dict__ for conduit in topology.conduits],
        },
        "topology_summary": _topology_summary(topology, imax=imax),
        "oracle_comparable_metrics": {
            "readdrainage_nodes_rows": node_count,
            "readdrainage_conduits_rows": conduit_count,
            "dwflow_nodes_rows": node_count,
            "dwflow_conduits_rows": conduit_count,
            "dw_nodal_flow_rows": node_count,
            "dw_conduit_flow_rows": conduit_count,
        },
    }


def run_stormdrain_runtime_consumer(
    *,
    drainage_path: str | Path | None,
    imax: int,
    fhpredi2: Mapping[int, float] | Sequence[float] | None = None,
    cell_area: float | None = None,
    dt: float | None = None,
    tnow: float = 0.0,
    tnext: float | None = None,
    ttout: float | None = None,
    arf: Mapping[int, float] | Sequence[float] | None = None,
    ele_delta: Mapping[int, float] | Sequence[float] | None = None,
    expected_node_count: int | None = None,
    expected_conduit_count: int | None = None,
    environ: Mapping[str, str] | None = None,
) -> dict[str, object]:
    """Run the source-backed stormdrain exchange diagnostics for one DFS step."""
    enabled = stormdrain_runtime_enabled(environ)
    manifest = _default_runtime_manifest(enabled=enabled, drainage_path=drainage_path)
    if not enabled:
        return manifest
    if drainage_path is None or not Path(drainage_path).is_file():
        manifest.update({"blocked_reason": "missing drainage topology: required stormdrain topology file drainage.txt", "fail_closed": True})
        return manifest

    try:
        topology = load_stormdrain_topology(drainage_path, imax=imax)
        if expected_node_count is not None and topology.node_count != int(expected_node_count):
            raise StormdrainTopologyError(
                f"drainage node count {topology.node_count} does not match expected {expected_node_count}"
            )
        if expected_conduit_count is not None and topology.conduit_count != int(expected_conduit_count):
            raise StormdrainTopologyError(
                f"drainage conduit count {topology.conduit_count} does not match expected {expected_conduit_count}"
            )
        if fhpredi2 is None or cell_area is None or dt is None:
            result = _topology_only_result(topology, imax=imax)
            manifest.update(result)
            return manifest
        if not math.isfinite(cell_area) or cell_area <= 0.0:
            manifest.update({"blocked_reason": f"invalid cell_area {cell_area!r}", "fail_closed": True})
            return manifest
        if not math.isfinite(dt) or dt <= 0.0:
            manifest.update({"blocked_reason": f"invalid dt {dt!r}", "fail_closed": True})
            return manifest
        fh_by_cell = _mapping_values(fhpredi2, name="fhpredi2")
        arf_by_cell = _mapping_values(arf or {}, name="arf")
        ele_delta_by_cell = _mapping_values(ele_delta or {}, name="ele_delta")
        result = _run_source_backed_step(
            topology=topology,
            fh_by_cell=fh_by_cell,
            arf_by_cell=arf_by_cell,
            ele_delta_by_cell=ele_delta_by_cell,
            cell_area=float(cell_area),
            dt=float(dt),
            tnow=float(tnow),
            tnext=float(tnext if tnext is not None else tnow + dt),
            ttout=float(ttout if ttout is not None else tnow + dt),
        )
    except Exception as exc:
        manifest.update({"blocked_reason": str(exc), "fail_closed": True})
        return manifest

    manifest.update(result)
    return manifest


def _run_source_backed_step(
    *,
    topology: StormdrainTopology,
    fh_by_cell: dict[int, float],
    arf_by_cell: dict[int, float],
    ele_delta_by_cell: dict[int, float],
    cell_area: float,
    dt: float,
    tnow: float,
    tnext: float,
    ttout: float,
) -> dict[str, object]:
    nodes = topology.nodes
    conduits = topology.conduits
    node_count = len(nodes)
    conduit_count = len(conduits)
    fh_after_by_cell = dict(fh_by_cell)

    newlatflow = [0.0] * (node_count + 1)
    rtnvol = [0.0] * (node_count + 1)
    total_to_node = [0.0] * (node_count + 1)
    total_from_node = [0.0] * (node_count + 1)
    node_exchange: list[dict[str, object]] = []

    for node in nodes:
        cell = node.nodeindex
        fh_before = float(fh_after_by_cell.get(cell, 0.0))
        ele_delta_value = float(ele_delta_by_cell.get(cell, 0.0))
        flow = 0.0
        if node.nodetype == 0 and fh_before > 0.0 and ele_delta_value <= 0.1:
            if fh_before <= 0.5:
                flow = (fh_before ** 1.5) * STORMDRAIN_LOW_DEPTH_WEIR_COEFF
            else:
                flow = 0.0
            max_flow = fh_before * cell_area / dt
            if flow * dt > fh_before * cell_area:
                flow = max_flow
        step_volume = flow * dt
        total_to_node[node.node_no] += step_volume
        fh_after = fh_before - step_volume / cell_area
        fh_after_by_cell[cell] = fh_after
        newlatflow[node.node_no] = flow
        if node.nodetype == 0:
            node_exchange.append(
                {
                    "event": "surface_to_node_pre_dwflow",
                    "nt": 1,
                    "tnow": tnow,
                    "dt": dt,
                    "tnext": tnext,
                    "ttout": ttout,
                    "node_no": node.node_no,
                    "node_name": node.name,
                    "node_type": node.nodetype,
                    "grid_index": cell,
                    "fh_before_drainage": fh_before,
                    "fh_after_removal": fh_after,
                    "cell_area_m2": cell_area,
                    "newlatflow": flow,
                    "voltonode_step_volume": step_volume,
                    "total_to_node": total_to_node[node.node_no],
                    "rtnvol": 0.0,
                    "total_from_node": 0.0,
                    "arf": float(arf_by_cell.get(cell, 0.0)),
                    "ele_delta_m": ele_delta_value,
                }
            )

    dwflow = _run_dry_dwflow_first_iteration(
        topology=topology,
        newlatflow=newlatflow,
        dt=dt,
        tnow=tnow,
        tnext=tnext,
        ttout=ttout,
        fh_after_by_cell=fh_after_by_cell,
    )

    for node in nodes:
        cell = node.nodeindex
        before_return = float(fh_after_by_cell.get(cell, 0.0))
        arf_value = float(arf_by_cell.get(cell, 0.0))
        if arf_value != 1.0:
            fh_after_by_cell[cell] = before_return + rtnvol[node.node_no] / cell_area
            total_from_node[node.node_no] += rtnvol[node.node_no]
        node_exchange.append(
            {
                "event": "node_to_surface_post_dwflow",
                "nt": 1,
                "tnow": tnow,
                "dt": dt,
                "tnext": tnext,
                "ttout": ttout,
                "node_no": node.node_no,
                "node_name": node.name,
                "node_type": node.nodetype,
                "grid_index": cell,
                "fh_before_drainage": before_return,
                "fh_after_removal": float(fh_after_by_cell.get(cell, 0.0)),
                "cell_area_m2": cell_area,
                "newlatflow": newlatflow[node.node_no],
                "voltonode_step_volume": newlatflow[node.node_no] * dt,
                "total_to_node": total_to_node[node.node_no],
                "rtnvol": rtnvol[node.node_no],
                "total_from_node": total_from_node[node.node_no],
                "arf": arf_value,
                "ele_delta_m": float(ele_delta_by_cell.get(cell, 0.0)),
            }
        )

    tempnodeinflowvol = float(sum(total_to_node))
    tempnodertnvol = 0.0
    balance = {
        "nt": 1,
        "tnow": tnow,
        "dt": dt,
        "tnext": tnext,
        "ttout": ttout,
        "tempnodeinflowvol_m3": tempnodeinflowvol,
        "tempnodertnvol_m3": tempnodertnvol,
        "totalvoltonode_sum_m3": tempnodeinflowvol,
        "totalvolfromnode_sum_m3": 0.0,
        "newlatflow_sum_m3s": float(sum(newlatflow)),
        "rtnvol_sum_m3": 0.0,
    }
    return {
        "stormdrain_available": True,
        "stormdrain_selected": True,
        "stormdrain_runtime_enabled": True,
        "stormdrain_branch_active": True,
        "topology_loaded": True,
        "drainage_topology_validated": True,
        "node_count": node_count,
        "conduit_count": conduit_count,
        "changed_field_names": ["stormdrain_fhpredi2"],
        "blocked_reason": None,
        "fail_closed": False,
        "default_off_verified": False,
        "topology": {
            "nodes": [node.__dict__ for node in nodes],
            "conduits": [conduit.__dict__ for conduit in conduits],
        },
        "node_exchange": node_exchange,
        "dwflow_nodes": dwflow["nodes"],
        "dwflow_conduits": dwflow["conduits"],
        "dwflow_iterations": dwflow["iterations"],
        "balance": balance,
        "fh_after_by_cell": {str(cell): value for cell, value in sorted(fh_after_by_cell.items())},
        "max_abs_newlatflow": max((abs(value) for value in newlatflow), default=0.0),
        "max_abs_voltonode_step_volume": max((abs(value * dt) for value in newlatflow), default=0.0),
        "max_abs_rtnvol": 0.0,
        "nonzero_newlatflow_rows": int(sum(1 for value in newlatflow if abs(value) > 0.0)),
    }


def _run_dry_dwflow_first_iteration(
    *,
    topology: StormdrainTopology,
    newlatflow: list[float],
    dt: float,
    tnow: float,
    tnext: float,
    ttout: float,
    fh_after_by_cell: Mapping[int, float],
) -> dict[str, list[dict[str, object]]]:
    node_count = topology.node_count
    nnewsurfarea = [0.0] * (node_count + 1)
    ninflow = [0.0] * (node_count + 1)
    noutflow = [0.0] * (node_count + 1)
    nnewdepth = [0.0] * (node_count + 1)
    nnewvolume = [0.0] * (node_count + 1)
    deltah = [0.0] * (node_count + 1)
    ispond = [0] * (node_count + 1)

    conduits_rows: list[dict[str, object]] = []
    iteration_rows: list[dict[str, object]] = []
    for conduit in topology.conduits:
        y1 = STORMDRAIN_DRY_FUDGE_M
        y2 = STORMDRAIN_DRY_FUDGE_M
        ymid = STORMDRAIN_DRY_FUDGE_M
        if conduit.xsecshpindx == 2:
            a1 = y1 * conduit.geom2
            a2 = y2 * conduit.geom2
            amid = ymid * conduit.geom2
        else:
            a1 = a2 = amid = 0.0
        surfarea1 = STORMDRAIN_DRY_FUDGE_M * conduit.length_m / 2.0
        surfarea2 = surfarea1
        dqdh = STORMDRAIN_GRAVITY * dt * amid / conduit.length_m if conduit.length_m else 0.0
        cnewvolume = amid * conduit.length_m
        row = {
            "tnow": tnow,
            "dt": dt,
            "tnext": tnext,
            "ttout": ttout,
            "iteration": 1,
            "conduit_no": conduit.conduit_no,
            "conduit_name": conduit.name,
            "inlet_node": conduit.inlet_node,
            "outlet_node": conduit.outlet_node,
            "cnewflow_m3s": 0.0,
            "cnewdepth_m": STORMDRAIN_DRY_FUDGE_M,
            "cnewvolume_m3": cnewvolume,
            "conduita1_m2": amid,
            "conduita2_m2": 0.0,
            "conduitq1_m3s": 0.0,
            "conduitq2_m3s": 0.0,
            "coldflow_m3s": 0.0,
            "colddepth_m": 0.0,
            "coldvolume_m3": 0.0,
            "dqdh": dqdh,
            "bypass": 1,
            "isfull": 0,
            "surfarea1_m2": surfarea1,
            "surfarea2_m2": surfarea2,
            "outlet_ninflow_m3s": newlatflow[conduit.outlet_node],
            "outlet_outfallvol_m3": 0.0,
        }
        conduits_rows.append(row)
        iteration_rows.append(
            {
                **row,
                "flow_class": 3,
                "isclosed": False,
                "has_outfall": topology.nodes[conduit.inlet_node - 1].nodetype == 1
                or topology.nodes[conduit.outlet_node - 1].nodetype == 1,
                "y1_m": y1,
                "y2_m": y2,
                "ymid_m": ymid,
                "a1_m2": a1,
                "a2_m2": a2,
                "amid_m2": amid,
                "r1_m": 0.0,
                "rmid_m": 0.0,
                "h1_m": topology.nodes[conduit.inlet_node - 1].invertel_m,
                "h2_m": topology.nodes[conduit.outlet_node - 1].invertel_m,
                "z1_m": topology.nodes[conduit.inlet_node - 1].invertel_m,
                "z2_m": topology.nodes[conduit.outlet_node - 1].invertel_m,
                "qlast_m3s": 0.0,
                "qold_m3s": 0.0,
            }
        )
        nnewsurfarea[conduit.inlet_node] += surfarea1
        nnewsurfarea[conduit.outlet_node] += surfarea2

    for node in topology.nodes:
        node_no = node.node_no
        ninflow[node_no] = newlatflow[node_no]
        if node.nodetype == 1:
            nnewdepth[node_no] = STORMDRAIN_DRY_FUDGE_M
            nnewvolume[node_no] = 0.0
        else:
            surfarea = max(nnewsurfarea[node_no] + STORMDRAIN_NODE_SURFACE_AREA_M2, STORMDRAIN_NODE_SURFACE_AREA_M2)
            d_volume = 0.5 * ninflow[node_no] * dt
            ynew = max(d_volume / surfarea, 0.0)
            nnewdepth[node_no] = ynew
            nnewvolume[node_no] = ynew * STORMDRAIN_NODE_STORAGE_AREA_M2
            deltah[node_no] = abs(ynew)

    node_rows: list[dict[str, object]] = []
    for node in topology.nodes:
        node_no = node.node_no
        node_rows.append(
            {
                "tnow": tnow,
                "dt": dt,
                "tnext": tnext,
                "ttout": ttout,
                "iteration": 1,
                "node_no": node_no,
                "node_name": node.name,
                "node_type": node.nodetype,
                "grid_index": node.nodeindex,
                "newlatflow_m3s": newlatflow[node_no],
                "ninflow_m3s": ninflow[node_no],
                "noutflow_m3s": noutflow[node_no],
                "noldnetinflow_m3s": 0.0,
                "nrtn_m3s": 0.0,
                "rtnvol_m3": 0.0,
                "nnewdepth_m": nnewdepth[node_no],
                "nolddepth_m": 0.0,
                "nnewvolume_m3": nnewvolume[node_no],
                "noldvolume_m3": 0.0,
                "nnewsurfarea_m2": nnewsurfarea[node_no],
                "deltah_m": deltah[node_no],
                "ispond": ispond[node_no],
                "fh_surface_m": float(fh_after_by_cell.get(node.nodeindex, 0.0)),
            }
        )
    return {"nodes": node_rows, "conduits": conduits_rows, "iterations": iteration_rows}
